### ISSUE TITLE
Starting a Local Community

### ISSUE THREAD

**Issue by Taiwrash** [cncf/students#7]
Hello!

After a lot of surveys to recognise our community interest in 2022. We discovered that majority of them are interested in cloud computing. For this reason, we find it important to have a source for learning resources and supports. I got to know about to know CNCF at Kubernetes Community Days Africa virtual conference in 2021. Your quick response on the next step will be appreciated. 

Regards,
Rasheed.

**Comment by xmulligan** [comment]
Sorry for the delay after the holidays! Glad to hear that your community is interested in cloud native 🎊 You should check out https://github.com/cncf/communitygroups for more information about how to set up your community group.

**Comment by Taiwrash** [comment]
Thanks so much for this

**Comment by xmulligan** [comment]
Let me know if there is anything else you need!

**Comment by Taiwrash** [comment]
I have actually filled the form and I expecting response from the team.

Thanks for the support @xmulligan

**Comment by xmulligan** [comment]
They should get back to you shortly, but if they don't please feel free to ping me here :)

**Comment by Taiwrash** [comment]
Okay, I will...
